import os
import sys
import time
import subprocess
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
HEARTBEAT_PATH = os.path.join(BASE_DIR, "infrastructure", "heartbeat.txt")
INCIDENT_LOG_PATH = os.path.join(BASE_DIR, "infrastructure", "incident_logs.txt")
TMUX_SESSION_NAME = "apex_scout"

class AutonomousSupervisorDaemon:
    """Monitors system vitality registers and executes automated process recovery actions."""
    def __init__(self, stale_threshold_seconds=45, max_recovery_attempts=3):
        self.stale_threshold = stale_threshold_seconds
        self.max_recovery_attempts = max_recovery_attempts
        self.recovery_counter = 0
        self.last_recovery_time = None
        
        print(f"[*] Initializing Autonomous Supervisor Daemon...")
        print(f"[*] Target Session: '{TMUX_SESSION_NAME}' | Stale Limit: {self.stale_threshold}s")
        self._log_incident("Supervisor daemon initialized and armed.")

    def _log_incident(self, message):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        log_entry = f"[{timestamp}] [SUPERVISOR] {message}\n"
        with open(INCIDENT_LOG_PATH, "a") as f:
            f.write(log_entry)
        print(f"💾 [INCIDENT REGISTERED] {message}")

    def check_tmux_session_exists(self):
        """Verifies if the background server layer is alive in the operating system."""
        try:
            result = subprocess.run(["tmux", "has-session", "-t", TMUX_SESSION_NAME], 
                                    stderr=subprocess.PIPE, stdout=subprocess.PIPE)
            return result.returncode == 0
        except Exception as e:
            print(f"[-] Operating System tmux query exception: {e}")
            return False

    def execute_self_healing_routine(self):
        """Intervenes directly into the tmux shell layer to force reset dead software blocks."""
        if self.recovery_counter >= self.max_recovery_attempts:
            self._log_incident("CRITICAL: Circuit breaker triggered. Maximum recovery limits breached. Standing down to prevent infinite loops.")
            print("🚨 [CIRCUIT BREAKER DETONATED] Manual infrastructure intervention required immediately.")
            return False

        self.recovery_counter += 1
        self._log_incident(f"ATTEMPTING LIVE ENGINE RECOVERY (Sequence {self.recovery_counter}/{self.max_recovery_attempts})...")

        try:
            if self.check_tmux_session_exists():
                print("[*] Target session found. Sending SIGINT (Ctrl+C) shutdown signal to target workers...")
                subprocess.run(["tmux", "send-keys", "-t", TMUX_SESSION_NAME, "C-c"], check=True)
                time.sleep(3) # Allow background file handles and loops to cleanly unbind
                
                print("[*] Re-igniting Multi-Asset sniper engine loop within background cell...")
                subprocess.run(["tmux", "send-keys", "-t", TMUX_SESSION_NAME, "python3 live_paper_engine.py", "Enter"], check=True)
                self._log_incident("Autonomous command injection complete. Pipeline restart issued successfully.")
            else:
                self._log_incident(f"ERROR: Session '{TMUX_SESSION_NAME}' missing. Re-building background isolation cell...")
                subprocess.run(["tmux", "new-session", "-d", "-s", TMUX_SESSION_NAME], check=True)
                time.sleep(1)
                subprocess.run(["tmux", "send-keys", "-t", TMUX_SESSION_NAME, "python3 live_paper_engine.py", "Enter"], check=True)
                self._log_incident("Background shell cell rebuilt from bare-metal. Engine active.")
            
            self.last_recovery_time = time.time()
            return True
        except Exception as e:
            self._log_incident(f"FATAL: Self-healing protocol hit system crash: {e}")
            return False

    def supervise_lifecycle(self):
        print("[+] Supervisor loop permanently active. Monitoring background channels...")
        
        while True:
            # Prevent rapid back-to-back resets right after a recovery action completes
            if self.last_recovery_time and (time.time() - self.last_recovery_time) < 60:
                time.sleep(10)
                continue

            if not os.path.exists(HEARTBEAT_PATH):
                print("[-] Alert: Heartbeat file not yet generated by master core.")
                time.sleep(10)
                continue

            try:
                with open(HEARTBEAT_PATH, "r") as f:
                    last_pulse = float(f.read().strip())
                
                delta = time.time() - last_pulse

                if delta > self.stale_threshold:
                    print(f"\n🚨 [VITALITY BREAKDOWN] Core engine heartbeat is STALE ({delta:.1f}s ago). Triggering recovery.")
                    self.execute_self_healing_routine()
                else:
                    # Clear out the recovery counter tracking if the system maintains nominal uptime for an extended window
                    if self.recovery_counter > 0 and delta < 5:
                        self._log_incident("System recovery verified successful. Engine pulse restored. Resetting threshold counters.")
                        self.recovery_counter = 0

                    sys.stdout.write(f"\r[+] Supervisor Active | Engine Pulse Delta: {delta:.2f}s | Status: NOMINAL")
                    sys.stdout.flush()

            except ValueError:
                pass # Prevent crashing out over a raw disk-write split-second collision
            except Exception as e:
                print(f"\n[-] Supervisor exception intercept: {e}")

            time.sleep(10)

if __name__ == "__main__":
    try:
        daemon = AutonomousSupervisorDaemon(stale_threshold_seconds=45, max_recovery_attempts=3)
        daemon.supervise_lifecycle()
    except KeyboardInterrupt:
        print("\n[!] Supervisor daemon successfully detached. Operational shield disarmed.")
        sys.exit(0)
